### ISSUE TITLE
Question regarding BEAM-BIMAP IO

### ISSUE THREAD

**Issue by erik132** [senbox-org/snap-engine#118]
Problem:
I'm trying to build some algorithms using BEAM-DIMAP format files on the GPU. I tried to do those using SNAP Operations feature, but unfortunately the tiles fed to me are too small. I sometimes need tiles the size of gigabytes and sometimes to use the GPU effectively I need to cut data in irregular shapes. The current tile cutter doesn't seem to be able to do that so I need to make my own. However I'm new to SNAP and so the IO doesn't make much sense to me.

Question:
Is there example code anywhere which reads in a BEAM-DIMAP file, accesses the pixel data of every band, increases every available pixel value by 50, with the exception of edges, which will be increased by 100. After that writes out the data in a different file. Anything similar which regards in changing individual pixel data and writing it out will also do.

**Comment by TonioF** [comment]
Your problem seems to be a bit different from your question, so I'll comment on both: As user, you cannot specify tile sizes. You can, however, write an operator and set the tilesizes of your output product: 
product.setPreferredTileSize(). Have a look here: https://senbox.atlassian.net/wiki/spaces/SNAP/pages/24051787/How+to+integrate+a+new+processor
There are also links to examples at the bottom.

This would also be my answer to your question, but I would simply do the operation in your example with bandmaths-expressions like this:
if X <1 or Y < 1 then band_name + 100 else band_name + 50

**Comment by erik132** [comment]
The numbers in my question are mere examples. The problem is that I do not know where to put them or where to get them. Should I manipulate the Planarimage of each band, should I do something related to rasters? What methods will get me the pixels and what methods will write the pixels? The thing is that I want to manipulate the image file of each band directly. 

Regarding the link you sent me, I have actually built a new operator, but I haven't yet used it to configure tile sizes. This I have to thank you for :)

**Comment by erik132** [comment]
I have found a solution for my question. Wasn't exactly what I thought it would be, but I can work with it.
